name: Run Detox Tests
on:
  push:
    branches:
      - main

jobs:
  build-and-test-android:
    name: Android - Build and run Detox tests
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: false
          
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 23

      - uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
            ~/.android/debug.keystore
          key: avd-35-ubuntu-playstore

      # copied from: https://github.com/ReactiveCircus/android-emulator-runner/blob/main/.github/workflows/main.yml
      - uses: gradle/actions/setup-gradle@v4

      - name: enable KVM for linux runners
        if: runner.os == 'Linux'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Add Secrets
        run: |
          echo '{"RECLAIM_APP_ID": "${{ secrets.RECLAIM_APP_ID }}", "RECLAIM_APP_SECRET": "${{ secrets.RECLAIM_APP_SECRET }}"}' >> secrets.json

      - name: Npm install
        run: npm install

      - name: Build Detox
        run: |
          cd android && ./gradlew clean && cd ..
          npm run detox:android:build

      - name: Setup Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          arch: x86_64
          target: playstore
          profile: Galaxy Nexus
          avd-name: Medium_Phone_API_36.0
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-metrics
          disable-animations: false
          script: echo "Emulator setup complete"

      - name: Run Detox Tests
        run: sh scripts/run-android-tests-ci.sh
