name: Run Detox Tests
on:
  push:
    branches:
      - main

jobs:
  build-and-test-android:
    name: Android - Build and run Detox tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Add Secrets
        run: |
          echo '{"RECLAIM_APP_ID": "${{ secrets.RECLAIM_APP_ID }}", "RECLAIM_APP_SECRET": "${{ secrets.RECLAIM_APP_SECRET }}"}' >> secrets.json

      - name: Npm install
        run: npm install

      - name: Build Detox
        run: npm run detox:android:build

      - name: Start Metro
        run: npm run detox:start &

      - name: Run Detox tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          avd-name: Medium_Phone_API_36.0
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-metrics
          disable-animations: false
          script: npm run detox:android:test:ci